// packages/theme-default/src/client/components/Sidebar/Sidebar.svelte
<script>
  import BackArrowIcon from ':virtual/vitebook/icons/back-arrow?raw';
  import { currentRoute } from '@vitebook/client';
  import { defaultThemeLocaleOptions } from '../../../shared';
  import { darkMode } from '../../stores/darkMode';
  import { isLargeScreen } from '../../stores/isLargeScreen';
  import { localizedThemeConfig } from '../../stores/localizedThemeConfig';
  import { hasNavbarItems } from '../Navbar/hasNavbarItems';
  import NavbarTitle from '../Navbar/NavbarTitle.svelte';
  import ThemeSwitch from '../ThemeSwitch.svelte';
  import { hasSidebarItems } from './hasSidebarItems';
  import SidebarButton from './SidebarButton.svelte';
  import { sidebarItems } from './sidebarItems';
  import SidebarTree from './SidebarTree.svelte';

  export let open = false;

  let isMainMenuShowing = false;

  $: backToMainMenuText =
    $localizedThemeConfig.sidebar?.backToMainMenuText ??
    defaultThemeLocaleOptions.sidebar.backToMainMenuText;

  $: hasMainMenuItems = !$isLargeScreen ? $hasNavbarItems : false;

  $: isMainMenuShowing =
    (!open && !$hasSidebarItems) || (!$hasSidebarItems && hasMainMenuItems);

  $: forceOpen = $isLargeScreen && $hasSidebarItems;

  // Close sidebar on route change if not forced open.
  $: if ($currentRoute && !forceOpen) open = false;

  // Hide main menu once enter large screen, otherwise hide sidebar on smaller devices.
  $: if ($isLargeScreen) {
    isMainMenuShowing = false;
  } else {
    open = false;
  }

  // If large screen and no sidebar items hide it.
  $: if ($isLargeScreen && !$hasSidebarItems) {
    open = false;
  }

  // force open.
  $: if (!open && forceOpen) {
    open = true;
  }

  function onShowMainMenu() {
    isMainMenuShowing = true;
  }
</script>

<aside
  class="sidebar"
  class:dark={$darkMode}
  class:open
  class:icon-colors={$localizedThemeConfig.sidebar?.iconColors}
  aria-hidden={!open}
>
  <slot name="start" />

  {#if !$isLargeScreen || $localizedThemeConfig.navbar === false}
    <div class="sidebar__header">
      <div class="sidebar__header-wrapper">
        <NavbarTitle />
        <div style="flex-grow: 1;" />
        <ThemeSwitch />
      </div>
    </div>
  {/if}

  <div class="sidebar__body">
    {#if hasMainMenuItems && !$isLargeScreen && !isMainMenuShowing}
      <SidebarButton
        class="sidebar__back-button"
        aria-hidden={isMainMenuShowing}
        on:pointerdown={onShowMainMenu}
        on:keydown={(e) => e.key === 'Enter' && onShowMainMenu()}
      >
        <span class="sidebar__back-button__arrow">
          {@html BackArrowIcon}
        </span>
        {backToMainMenuText}
      </SidebarButton>
    {/if}

    {#if hasMainMenuItems}
      <div class="sidebar__main-menu" aria-hidden={!isMainMenuShowing}>
        {#await import('../Navbar/NavLinks.svelte') then NavLinks}
          <svelte:component
            this={NavLinks.default}
            active={isMainMenuShowing}
          />
        {/await}
      </div>
    {/if}

    {#if $hasSidebarItems}
      <ul class="sidebar__current-menu" aria-hidden={isMainMenuShowing}>
        <SidebarTree items={$sidebarItems} />
      </ul>
    {/if}
  </div>

  <slot name="end" />
</aside>

<style>
  .sidebar {
    --vbk--nav-item-color: var(--vbk--sidebar-item-color);
    --vbk--nav-item-bg-color: var(--vbk--sidebar-item-bg-color);
    --vbk--nav-item-hover-color: var(--vbk--sidebar-item-hover-color);
    --vbk--nav-item-hover-bg-color: var(--vbk--sidebar-item-hover-bg-color);
    --vbk--nav-link-active-bg-color: transparent;

    position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
    flex: 0 0 auto;
    z-index: var(--vbk--sidebar-z-index);
    width: 80vw;
    background-color: var(--vbk--sidebar-bg-color);
    overflow-y: auto;
    border: var(--vbk--sidebar-border);
    transform: translateX(-100%) translateZ(0);
    transition: transform 250ms ease-in;
    will-change: transform;
    box-shadow: var(--vbk--elevation-medium);
  }

  .sidebar.open {
    transform: translateX(0) translateZ(0);
  }

  .sidebar__header {
    padding-top: 0.25rem;
  }

  .sidebar__header-wrapper {
    display: flex;
    padding: 1rem;
  }

  .sidebar__back-button__arrow {
    margin-right: 0.25rem;
  }

  .sidebar__body {
    padding: 0 1rem;
    margin-top: 0.375rem;
  }

  .sidebar__main-menu {
    display: none;
  }

  .sidebar__main-menu[aria-hidden='false'] {
    display: block;
  }

  .sidebar__current-menu {
    padding: 0;
    margin: 0;
    margin-top: 1rem;
  }

  .sidebar__current-menu[aria-hidden='true'] {
    display: none;
  }

  @media (min-width: 992px) {
    .sidebar {
      position: sticky;
      width: auto;
      min-width: var(--vbk--sidebar-min-width);
      max-height: 100vh;
      opacity: 1;
      z-index: 1;
      transition: unset;
      padding-top: var(--vbk--navbar-height);
      box-shadow: unset;
    }

    .sidebar.open {
      border-right: 0.125rem solid var(--vbk--color-gray-200);
    }

    .sidebar.open.dark {
      border-right: 0.125rem solid var(--vbk--color-gray-500);
    }

    .sidebar:not(.sidebar.open) {
      width: 0;
      min-width: 0;
      opacity: 0;
      visibility: hidden;
    }
  }
</style>

// packages/theme-vue-default/src/client/components/Sidebar/Sidebar.vue
<script setup lang="ts">
import { useWindowSize } from '@vueuse/core';
import { computed, ref, watch, watchEffect } from 'vue';
import { useRoute } from 'vue-router';

import { useLocalizedThemeConfig } from '../../composables/useLocalizedThemeConfig';
import NavbarTitle from '../Navbar/NavbarTitle.vue';
import NavLinks from '../Navbar/NavLinks.vue';
import { useHasNavbarItems } from '../Navbar/useNavbar';
import ThemeSwitch from '../ThemeSwitch.vue';
import SidebarLinks from './SidebarLinks.vue';
import { useHasSidebarItems, useIsSidebarOpen } from './useSidebar';

const route = useRoute();
const isSidebarOpen = useIsSidebarOpen();

watch(
  () => route.path,
  () => {
    isSidebarOpen.value = false;
  }
);

const themeConfig = useLocalizedThemeConfig();

const hasNavItems = useHasNavbarItems();
const hasSidebarItems = useHasSidebarItems();

const isMainMenuShowing = ref(false);

const windowSize = useWindowSize();

const hasMainMenuItems = computed(() =>
  windowSize.width.value < 992 ? hasNavItems.value : false
);

const forceSidebarOpen = computed(
  () => windowSize.width.value >= 992 && hasSidebarItems.value
);

watchEffect(() => {
  if (!isSidebarOpen.value && forceSidebarOpen.value) {
    isSidebarOpen.value = true;
  }
});

watchEffect(() => {
  isMainMenuShowing.value =
    (!isSidebarOpen.value && !hasSidebarItems.value) ||
    (!hasSidebarItems.value && hasMainMenuItems.value);
});

function handleToggleMenus() {
  isMainMenuShowing.value = !isMainMenuShowing.value;
}
</script>

<template>
  <aside
    class="sidebar"
    :class="{ open: isSidebarOpen || forceSidebarOpen }"
    :aria-hidden="isSidebarOpen && !forceSidebarOpen"
  >
    <slot name="start" />

    <div class="header">
      <div class="header-wrapper">
        <NavbarTitle />
        <div class="flex-grow"></div>
        <ThemeSwitch />
      </div>
    </div>

    <div class="links">
      <button
        v-if="hasMainMenuItems"
        class="back-button"
        :aria-hidden="isMainMenuShowing"
        @pointerdown="handleToggleMenus"
        @keydown.enter="handleToggleMenus"
      >
        {{ themeConfig.sidebar.backToMainMenuText }}
      </button>

      <NavLinks
        v-if="hasMainMenuItems"
        class="main-menu"
        :class="{ open: isMainMenuShowing }"
        :aria-hidden="!isMainMenuShowing"
      />

      <SidebarLinks
        v-if="hasSidebarItems"
        class="current-menu"
        :class="{ open: !isMainMenuShowing }"
        :aria-hidden="isMainMenuShowing"
      />
    </div>

    <slot name="end" />
  </aside>
</template>

<style scoped>
.sidebar {
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  z-index: var(--sidebar-z-index);
  width: 80vw;
  background-color: var(--color-bg-200);
  overflow-y: auto;
  transform: translateX(-100%);
  transition: transform 0.35s ease;
}

.sidebar.open {
  transform: translateX(0);
}

.header {
  padding-top: 0.25rem;
}

.header-wrapper {
  display: flex;
  padding: 1rem;
}

.flex-grow {
  flex: 1;
}

.back-button[aria-hidden='true'] {
  display: none;
}

.links {
  padding: 0 1rem;
  margin-top: 0.375rem;
}

:deep(.nav-item) {
  margin-top: 0.25rem;
}

.main-menu {
  display: none;
}

.main-menu.open {
  display: block;
}

.current-menu[aria-hidden='true'] {
  display: none;
}

@media (min-width: 992px) {
  .header {
    display: none;
  }

  .back-button {
    display: none;
  }

  .sidebar {
    width: var(--sidebar-width);
    margin-top: var(--navbar-height);
    transition: unset;
  }

  .sidebar.open {
    transition: transform 0.135s ease;
  }
}
</style>
