// packages/theme-default/src/client/layout/Page.vue
<script setup lang="ts">
import { PageView, usePage } from '@vitebook/client';

const page = usePage();
</script>

<template>
  <main :class="{ [`${page?.type}`]: page?.type }">
    <div>
      <slot name="start" />
      <PageView />
      <slot name="end" />
    </div>
  </main>
</template>

<style scoped>
main {
  flex: 1 0 0;
  position: relative;
  margin: 0;
  min-height: 100vh;
  padding-top: var(--navbar-height);
  background-color: var(--color-bg-200);
}

main[class~='md'],
main[class~='vue:md'],
main[class~='story'] {
  background-color: var(--color-bg-100);
}

main[class~='story'] {
  display: flex;
  width: 100%;
  height: 100%;
  align-items: center;
  justify-content: center;
}

main[class~='story'] > div {
  transform: translateY(-2rem);
}
</style>

// packages/theme-default/src/client/layout/Page.svelte
<script>
  import { PageView, currentPage } from '@vitebook/client';
  import { localizedThemeConfig } from '../stores/localizedThemeConfig';

  $: noNavbar = $localizedThemeConfig.navbar === false;
  $: isMarkdownPage = $currentPage?.type?.endsWith('md');
</script>

<main
  class={`page ${$currentPage?.type ? `type-${$currentPage.type}` : ''}`}
  class:no-navbar={noNavbar}
>
  <div class="page__container">
    <slot name="start" />
    <PageView />
    {#if isMarkdownPage}
      {#await import('../components/Markdown/MarkdownFooter.svelte') then c}
        <svelte:component this={c.default} />
      {/await}
    {/if}
    <slot name="end" />
  </div>
</main>

<style>
  main {
    display: block;
  }

  .page {
    position: relative;
    margin: 0;
    min-height: 100vh;
    padding-top: var(--vbk--navbar-height);
    flex: none;
    width: 100%;
  }

  .page[class*='md'] {
    background-color: var(--vbk--page-md-bg-color);
  }

  .page[class*='type-']:not([class*='md']) {
    display: flex;
    width: 100%;
    height: 100%;
    align-items: center;
    justify-content: center;
  }

  .page__container {
    width: 100%;
  }

  .page[class*='md'] > .page__container {
    margin: 0 auto;
    max-width: 48rem;
    padding: 0 2rem 4rem;
    padding-top: 1rem;
    padding-bottom: 103%;
  }

  .page[class*='type-']:not([class*='md']) > .page__container {
    display: flex;
    align-items: center;
    justify-content: center;
    transform: translateY(-2rem) translateZ(0);
  }

  @media (min-width: 992px) {
    .page {
      flex: 1 0 0;
      width: auto;
    }

    .page.no-navbar[class*='md'] > .page__container {
      margin-top: 1.5rem;
    }
  }
</style>
