// packages/theme-default/src/client/components/Navbar/NavItemLink.svelte
<script>
  import {
    currentRoute,
    localizedSiteOptions,
    OutboundLink
  } from '@vitebook/client';
  import { getLinkProps } from '../../helpers/getLinkProps';

  export let item;

  $: linkProps = getLinkProps(item, $localizedSiteOptions, $currentRoute);
</script>

<!-- svelte-ignore a11y-missing-attribute - set by linkProps -->
<a class:nav-item={true} class:nav-link={true} {...linkProps}>
  <span class="nav-link__text">
    {item.text}
    {#if linkProps.class.includes('external')}
      <OutboundLink />
    {/if}
  </span>
</a>

<style>
  /** No mobile styles because a nav item is a sidebar item <992px. **/

  @media (hover: hover) and (min-width: 992px) {
    .nav-link:hover {
      text-decoration: none;
    }

    .nav-item:hover {
      color: var(--vbk--nav-item-hover-color);
      background-color: var(--vbk--nav-item-hover-bg-color);
    }

    .nav-link:hover > .nav-link__text {
      color: var(--vbk--nav-item-hover-color);
      border-bottom: var(--vbk--nav-link-hover-border);
    }
  }

  @media (min-width: 992px) {
    .nav-item {
      color: var(--vbk--nav-item-color);
      background-color: var(--vbk--nav-item-bg-color);
    }

    .nav-link {
      display: flex;
      align-items: center;
      font-size: 1rem;
      border: 0;
      font-weight: 500;
      line-height: 1.4;
      margin-top: 0.5rem;
      padding: 0.5rem 1rem;
      border-radius: 0;
      color: var(--vbk--nav-item-color);
      white-space: nowrap;
      text-decoration: none;
      width: 100%;
      cursor: pointer;
      text-align: left;
      background-color: transparent;
    }

    .nav-link.active .nav-link__text {
      color: var(--vbk--nav-link-active-color);
      background-color: var(--vbk--nav-link-active-bg-color);
      border-bottom: var(--vbk--nav-link-active-border);
      transition: border-color var(--vbk--color-transition-duration)
        var(--vbk--color-transition-timing);
    }
  }
</style>

// packages/theme-vue-default/src/client/components/Navbar/NavItemLink.vue
<script setup lang="ts">
import { NavItemLink } from '@vitebook/core/shared';
import { toRefs } from 'vue';

import { useNavItemLink } from './useNavItemLink';

const props = defineProps<{
  item: NavItemLink;
}>();

const propsRef = toRefs(props);

const { props: linkProps, isExternal } = useNavItemLink(propsRef.item);

function preventClick(event: Event) {
  if (!isExternal) {
    event.preventDefault();
  }
}

function handleLinkClick(event: Event, navigate: () => void): void {
  if (!isExternal) {
    event.preventDefault();
    navigate();
  }
}
</script>

<template>
  <div class="nav-link">
    <router-link v-slot="{ navigate, href }" :to="linkProps.to" custom>
      <a
        v-bind="linkProps"
        :to="undefined"
        :href="isExternal ? linkProps.to : href"
        @click="preventClick"
        @pointerdown="(e) => handleLinkClick(e, navigate)"
        @keydown.enter="(e) => handleLinkClick(e, navigate)"
      >
        <span class="link-text">
          {{ item.text }} <OutboundLink v-if="isExternal" />
        </span>
      </a>
    </router-link>
  </div>
</template>

<style scoped>
.link {
  display: block;
  padding: 0.68rem 0.5rem;
  font-size: 1rem;
  font-weight: 500;
  border-radius: 0.12rem;
  color: var(--color-text);
  white-space: nowrap;
}

.link.active > .link-text {
  color: var(--color-primary);
}

.link.active {
  text-decoration: none;
}

.link:hover {
  text-decoration: none;
}

@media (hover: hover) and (pointer: fine) and (max-width: 991px) {
  .link:hover {
    background-color: var(--color-bg-100);
  }
}

@media (hover: hover) and (min-width: 992px) {
  .link:hover > .link-text {
    color: var(--color-text);
    border-bottom: 0.12rem solid var(--color-primary);
  }
}

@media (min-width: 992px) {
  .link {
    margin-top: 0.5rem;
    padding: 0.5rem 1rem;
    border-radius: 0;
  }

  .link.active > .link-text {
    color: var(--color-text);
    border-bottom: 0.12rem solid var(--color-primary);
  }
}
</style>
