// packages/theme-default/src/client/components/Navbar/NavItemWithMenu.svelte
<script>
  import MenuCaretIcon from ':virtual/vitebook/icons/menu-caret?raw';
  import { currentRoute, inBrowser } from '@vitebook/client';
  import { onMount } from 'svelte';
  import { afterUpdate } from 'svelte';
  import { tick } from 'svelte';
  import { languageLinks } from '../../stores/languageLinks';
  import { useMediaQuery } from '../../stores/useMediaQuery';
  import NavItemLink from './NavItemLink.svelte';

  export let item;

  let navItemRef;
  let menuButtonRef;

  let isMenuOpen = false;
  let isMenuActive = false;

  const isLargeScreen = useMediaQuery('(min-width: 992px)');

  $: isLanguagesGroup = item.text === $languageLinks?.text;

  $: menuId = `nav-menu-${item.text.replace(/\s/g, '-').toLowerCase()}`;
  $: menuButtonId = `nav-menu-button-${item.text
    .replace(/\s/g, '-')
    .toLowerCase()}`;

  $: if ($currentRoute && inBrowser) {
    if ($isLargeScreen) {
      isMenuOpen = false;
    } else if (navItemRef) {
      tick().then(() => {
        if (!navItemRef?.querySelector('a.active')) {
          isMenuOpen = false;
        }
      });
    }
  }

  onMount(() => {
    checkHasActiveItem();
    if (!$isLargeScreen && !isLanguagesGroup) {
      isMenuOpen = isMenuActive;
    }
  });

  afterUpdate(() => {
    tick().then(() => {
      checkHasActiveItem();
    });
  });

  function checkHasActiveItem() {
    if (!isLanguagesGroup) {
      isMenuActive = !!navItemRef?.querySelector('a.active');
    }
  }

  function onToggle() {
    isMenuOpen = !isMenuOpen;
  }

  function onMenuPointerLeave() {
    if ($isLargeScreen) {
      isMenuOpen = false;
    }
  }

  // TODO: poor man's accessbility, fix later.
  function onKeyDown(e) {
    if (!isMenuOpen) return;

    if (e.key === 'Esc' || e.key === 'Escape') {
      isMenuOpen = false;
      menuButtonRef?.focus();
    } else if (e.key === 'Tab') {
      tick().then(() => {
        if (!navItemRef?.contains(document.activeElement)) {
          isMenuOpen = false;
        }
      });
    }
  }
</script>

<div
  class="nav-item with-menu"
  on:keydown={onKeyDown}
  class:open={isMenuOpen}
  class:active={isMenuActive}
  bind:this={navItemRef}
>
  <button
    id={menuButtonId}
    class="nav-item__menu-button"
    aria-label={item.ariaLabel}
    aria-controls={menuId}
    aria-haspopup="true"
    on:pointerdown={onToggle}
    on:keydown={(e) => e.key === 'Enter' && onToggle()}
    bind:this={menuButtonRef}
  >
    <span class="nav-item__menu-button__text">{item.text}</span>
    <div class="nav-item__menu-button__caret">
      {@html MenuCaretIcon}
    </div>
  </button>

  <ul
    id={menuId}
    class="nav-item__menu"
    aria-labelledby={menuButtonId}
    aria-expanded={isMenuOpen}
    on:pointerleave={onMenuPointerLeave}
  >
    {#each item.menu as menuItem (menuItem.text)}
      <li class="nav-item__menu-item">
        <NavItemLink item={menuItem} />
      </li>
    {/each}
  </ul>
</div>

<style>
  /** No mobile styles because a nav item menu is a sidebar group <992px. **/

  .nav-item__menu-button__caret {
    padding-left: 0.12rem;
    transform: rotate(270deg) translateX(-0.25rem) translateZ(0);
    transform-origin: center;
  }

  .nav-item.open .nav-item__menu-button__caret {
    transform: translateY(0.1rem) translateZ(0);
  }

  @media (hover: hover) and (min-width: 992px) {
    .nav-item:hover {
      color: var(--vbk--nav-item-hover-color);
      background-color: var(--vbk--nav-item-hover-bg-color);
    }
  }

  @media (hover: hover) {
    .nav-item__menu-item:hover {
      color: var(--vbk--menu-item-hover-color);
      background-color: var(--vbk--menu-item-hover-bg-color);
    }

    :global(.nav-item__menu-item .nav-link:not(.active) > .nav-link__text) {
      border-bottom: 0 !important;
    }

    .nav-item.with-menu:hover .nav-item__menu {
      opacity: 1;
      visibility: visible;
    }
  }

  @media (min-width: 992px) {
    .nav-item {
      color: var(--vbk--nav-item-color);
      background-color: var(--vbk--nav-item-bg-color);
    }

    .nav-item > button {
      display: flex;
      align-items: center;
      font-size: 1rem;
      border: 0;
      font-weight: 500;
      line-height: 1.4;
      margin-top: 0.5rem;
      padding: 0.5rem 1rem;
      border-radius: 0;
      color: var(--vbk--nav-item-color);
      white-space: nowrap;
      text-decoration: none;
      width: 100%;
      cursor: pointer;
      text-align: left;
      background-color: transparent;
    }

    .nav-item__menu-button__caret,
    .nav-item.open .nav-item__menu-button__caret {
      transform: translateY(0) translateZ(0);
    }

    .nav-item.with-menu {
      position: relative;
      cursor: pointer;
      overflow: visible;
      width: 100%;
    }

    .nav-item__menu {
      display: block;
      position: absolute;
      top: 100%;
      right: 1rem;
      padding: 0.8rem;
      padding-bottom: 1rem;
      margin: 0;
      opacity: 0;
      visibility: hidden;
      z-index: calc(var(--vbk--navbar-z-index) + 1);
      border-radius: 0.15rem;
      box-shadow: var(--vbk--elevation-medium);
      min-width: 10rem;
      border: var(--vbk--menu-border);
      background-color: var(--vbk--menu-bg-color);
      transition: var(--vbk--menu-transition);
    }

    .nav-item.open .nav-item__menu {
      opacity: 1;
      visibility: visible;
    }
  }
</style>

// packages/theme-vue-default/src/client/components/Navbar/NavItemWithMenu.vue
<script setup lang="ts">
import { inBrowser, NavItemWithMenu } from '@vitebook/core/shared';
import { computed, ref, toRefs, watch } from 'vue';
import { useRoute } from 'vue-router';

import NavItemLink from './NavItemLink.vue';
import NavMenuArrow from './NavMenuArrow.vue';

const props = defineProps<{
  item: NavItemWithMenu;
}>();

const propsRef = toRefs(props);
const route = useRoute();
const isMenuOpen = ref(false);

const navItem = ref<HTMLElement | null>(null);
const menuButton = ref<HTMLButtonElement | null>(null);

watch(
  () => route.path,
  () => {
    if (!inBrowser) return;

    if (window.innerWidth >= 992) {
      isMenuOpen.value = false;
    } else {
      window.requestAnimationFrame(() => {
        if (!navItem.value?.querySelector('a.active')) {
          isMenuOpen.value = false;
        }
      });
    }
  }
);

const menuId = computed(
  () => `nav-menu-${propsRef.item.value.text.replace(/\s/g, '-').toLowerCase()}`
);

const menuButtonId = computed(
  () =>
    `nav-menu-button-${propsRef.item.value.text
      .replace(/\s/g, '-')
      .toLowerCase()}`
);

function onToggle() {
  isMenuOpen.value = !isMenuOpen.value;
}

// TODO: poor man's accessbility, fix later.
function onKeyDown(e: KeyboardEvent) {
  if (!isMenuOpen.value) return;

  if (e.key === 'Esc' || e.key === 'Escape') {
    isMenuOpen.value = false;
    menuButton.value?.focus();
  } else if (e.key === 'Tab') {
    window.requestAnimationFrame(() => {
      if (!navItem.value?.contains(document.activeElement)) {
        isMenuOpen.value = false;
      }
    });
  }
}

function onMenuPointerLeave() {
  if (window.innerWidth >= 992) {
    isMenuOpen.value = false;
  }
}
</script>

<template>
  <div
    ref="navItem"
    class="nav-menu"
    :class="{ 'menu-open': isMenuOpen }"
    @keydown="onKeyDown"
  >
    <button
      :id="menuButtonId"
      ref="menuButton"
      class="menu-button"
      :aria-label="item.ariaLabel"
      :aria-controls="menuId"
      aria-haspopup="true"
      @pointerdown="onToggle"
      @keydown.enter="onToggle"
    >
      <span class="menu-button-text">{{ item.text }}</span>
      <NavMenuArrow class="menu-button-arrow" :is-open="isMenuOpen" />
    </button>

    <ul
      :id="menuId"
      class="menu"
      :aria-labelledby="menuButtonId"
      :aria-expanded="isMenuOpen"
      @pointerleave="onMenuPointerLeave"
    >
      <li v-for="menuItem in item.menu" :key="menuItem.text" class="menu-item">
        <NavItemLink :item="menuItem" />
      </li>
    </ul>
  </div>
</template>

<style scoped>
.nav-menu {
  position: relative;
  height: 2.72rem;
  overflow: hidden;
  cursor: pointer;
}

.nav-menu.menu-open {
  height: auto;
}

.menu-button {
  width: 100%;
  border: 0;
  cursor: pointer;
  font-size: 1rem;
  line-height: 1.4;
  font-weight: 500;
  padding: 0.68rem 0.5rem;
  color: var(--color-text);
  background-color: transparent;
  text-align: left;
  white-space: nowrap;
}

.menu-button-arrow {
  padding-left: 0.12rem;
  transform: rotate(270deg) translateX(-0.25rem);
  transform-origin: center;
}

.menu-open .menu-button-arrow {
  transform: translateY(0.1rem);
}

.menu {
  margin: 0;
  padding: 0;
  list-style: none;
}

.menu-item {
  border-radius: 0.12rem;
  padding: 0.68rem 0.5rem;
}

.menu-item :deep(.nav-link) {
  margin-left: 1rem;
}

.menu-item :deep(.link) {
  margin: 0;
  padding: 0;
  font-size: 1rem;
  font-weight: 400;
}

@media (hover: hover) {
  .menu-button:hover {
    background-color: var(--color-bg-100);
  }

  .menu-item:hover {
    background-color: var(--color-bg-100);
  }

  .menu-item :deep(.link:hover:not(.active) > .link-text) {
    border-bottom: 0;
  }

  .nav-menu:hover .menu {
    display: block;
  }
}

@media (pointer: coarse), (min-width: 992px) {
  .menu-button:hover {
    background-color: transparent;
  }
}

@media (min-width: 992px) {
  .nav-menu {
    height: auto;
    overflow: visible;
  }

  .menu-button {
    margin-top: 0.5rem;
    padding: 0.5rem 1rem;
    border-radius: 0;
  }

  .menu-button-arrow,
  .menu-open .menu-button-arrow {
    transform: translateY(0.1rem);
  }

  .menu {
    display: none;
    position: absolute;
    top: 100%;
    right: 1rem;
    padding: 0.8rem;
    z-index: calc(var(--navbar-z-index) + 1);
    border-radius: 0.125rem;
    min-width: 10rem;
    border: 0.12rem solid var(--color-divider);
    background-color: var(--color-bg-200);
  }

  .menu-item {
    padding: 0.75rem 1rem;
    margin: 0;
  }

  .menu-item:first-child {
    margin-top: 0;
  }

  .menu-item :deep(.nav-link) {
    margin-left: 0;
  }

  .nav-menu.menu-open .menu {
    display: block;
  }
}
</style>
