// packages/theme-default/src/client/components/Navbar/NavLinks.svelte
<script>
  import { languageLinks } from '../../stores/languageLinks';
  import { repoLink } from '../../stores/repoLink';
  import { hasNavbarItems } from './hasNavbarItems';
  import { navbarConfig } from './navbarConfig';
  import NavItemLink from './NavItemLink.svelte';
  import NavItemWithMenu from './NavItemWithMenu.svelte';
</script>

{#if $hasNavbarItems}
  <nav class="navbar__links">
    <ul class="navbar__links__list">
      {#each $navbarConfig?.items ?? [] as item (item.text)}
        <li class="navbar__links__list-item">
          {#if 'menu' in item}
            <NavItemWithMenu {item} />
          {:else}
            <NavItemLink {item} />
          {/if}
        </li>
      {/each}

      {#if $languageLinks}
        <li class="navbar__links__list-item">
          <NavItemWithMenu item={$languageLinks} />
        </li>
      {/if}

      {#if $repoLink}
        <li class="navbar__links__list-item">
          <NavItemLink item={$repoLink} />
        </li>
      {/if}
    </ul>
  </nav>
{/if}

<style>
  .navbar__links {
    display: none;
  }

  @media (min-width: 992px) {
    .navbar__links {
      display: block;
    }

    .navbar__links__list {
      display: flex;
      flex-direction: row;
      align-items: center;
    }
  }
</style>

// packages/theme-vue-default/src/client/components/Navbar/NavLinks.vue
<script setup lang="ts">
import { useLocalizedThemeConfig } from '../../composables/useLocalizedThemeConfig';
import NavItemLink from './NavItemLink.vue';
import NavItemWithMenu from './NavItemWithMenu.vue';
import { useLanguageLinks } from './useLanguageLinks';
import { useHasNavbarItems } from './useNavbar';
import { useRepoLink } from './useRepoLink';

const themeConfig = useLocalizedThemeConfig();
const repoLink = useRepoLink();
const languageLinks = useLanguageLinks();
const hasNavItems = useHasNavbarItems();
</script>

<template>
  <nav v-if="hasNavItems">
    <ul>
      <template v-if="hasNavItems">
        <li
          v-for="item in themeConfig.navbar.items"
          :key="item.text"
          class="nav-item"
        >
          <NavItemWithMenu v-if="'menu' in item" :item="item" />
          <NavItemLink v-else :item="item" />
        </li>
      </template>

      <li v-if="languageLinks" class="nav-item">
        <NavItemWithMenu :item="languageLinks" />
      </li>

      <li v-if="repoLink" class="nav-item">
        <NavItemLink :item="repoLink" />
      </li>
    </ul>
  </nav>
</template>

<style scoped>
nav > ul {
  margin: 0;
  padding: 0;
  list-style: none;
  display: flex;
  flex-direction: column;
}

ul > li {
  margin: 0;
  padding: 0;
}

@media (min-width: 992px) {
  nav > ul {
    flex-direction: row;
    align-items: center;
  }
}
</style>
