// packages/theme-default/src/client/layout/Page.svelte
<script>
  import { PageView, currentPage } from '@vitebook/client';
  import { localizedThemeConfig } from '../stores/localizedThemeConfig';

  $: noNavbar = $localizedThemeConfig.navbar === false;
  $: isMarkdownPage = $currentPage?.type?.endsWith('md');
</script>

<main
  class={`page ${$currentPage?.type ? `type-${$currentPage.type}` : ''}`}
  class:no-navbar={noNavbar}
>
  <div class="page__container">
    <slot name="start" />

    <PageView />

    {#if isMarkdownPage}
      {#await import('../components/Markdown/MarkdownFooter.svelte') then c}
        <svelte:component this={c.default} />
      {/await}
    {/if}

    <slot name="end" />
  </div>
</main>

<style>
  .page {
    display: block;
    position: relative;
    margin: 0;
    width: 100%;
    min-height: 100%;
  }

  .page[class*='md'] {
    background-color: var(--vbk--page-md-bg-color);
  }

  .page[class*='type-']:not([class*='md']) {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .page__container {
    width: 100%;
  }

  .page[class*='md'] > .page__container {
    margin: 0 auto;
    max-width: 48rem;
    padding: 0 2rem 4rem;
    padding-top: 1rem;
  }

  @media (min-width: 1400px) {
    .page[class*='md'] > .page__container {
      padding-left: 0;
      padding-right: 0;
    }
  }

  .page[class*='type-']:not([class*='md']) > .page__container {
    display: flex;
    align-items: center;
    justify-content: center;
  }

  @media (min-width: 992px) {
    .page.no-navbar[class*='md'] > .page__container {
      padding-top: 1.5rem;
    }
  }
</style>

// packages/theme-vue-default/src/client/layout/Page.vue
<script setup lang="ts">
import { PageView } from '@vitebook/vue/client';

import { useIsSidebarOpen } from '../components/Sidebar/useSidebar';

const isSidebarOpen = useIsSidebarOpen();
</script>

<template>
  <div class="container" :class="{ 'with-sidebar': isSidebarOpen }">
    <slot name="start" />
    <div class="page-view">
      <PageView />
    </div>
    <slot name="end" />
  </div>
</template>

<style scoped>
.container {
  padding-top: var(--navbar-height);
}

.page-view {
  width: 100%;
  display: inline-block;
  position: relative;
  margin: 0;
  min-height: calc(100vh - var(--navbar-height));
  background-color: var(--color-bg-100);
}

@media (min-width: 992px) {
  .container.with-sidebar {
    padding-left: var(--sidebar-width);
    transition: padding 0.135s ease;
  }
}
</style>
