// packages/vue/src/client/components/tabs/TabPanel.vue
<script setup lang="ts">
import { onBeforeUnmount, ref } from 'vue';
import { useTabsRegistry } from './useTabsRegistry';

const { value } = defineProps<{
  value: string;
}>();

const { currentValue } = useTabsRegistry();

const selected = ref(false);

onBeforeUnmount(
  currentValue.subscribe(($currentValue) => {
    selected.value = $currentValue === value;
  }),
);
</script>

<template>
  <div class="tabs__panel" role="tabpanel" :hidden="!selected">
    <slot />
  </div>
</template>

// packages/preact/src/client/components/tabs/TabPanel.tsx
import type { ComponentChildren } from 'preact';
import { useEffect, useState } from 'preact/hooks';
import { get } from 'svelte/store';

import { useTabsRegistry } from './useTabsRegistry';

export type TabPanelProps = {
  value: string;
  children: ComponentChildren;
};

function TabPanel({ value, children }: TabPanelProps) {
  const { currentValue } = useTabsRegistry();
  const [$currentValue, $setCurrentValue] = useState(get(currentValue));

  useEffect(() => {
    return currentValue.subscribe((v) => {
      $setCurrentValue(v);
    });
  });

  const selected = $currentValue === value;

  return (
    <div class="tabs__panel" role="tabpanel" hidden={!selected}>
      {children}
    </div>
  );
}

TabPanel.displayName = 'TabPanel';

export default TabPanel;
