// packages/vue/src/client/components/tabs/Tabs.vue
<script setup lang="ts">
import { isString } from '@vitebook/core';
import { createTabsRegistry } from '@vitebook/client/components/tabs';
import type { TabsRegistryItem } from '@vitebook/client/components/tabs';
import { onBeforeMount, onBeforeUnmount } from 'vue';
import { provideTabsRegistry } from './useTabsRegistry';
import TabItem from './TabItem.vue';

const { values, defaultValue, groupId } = withDefaults(
  defineProps<{
    values?: TabsRegistryItem[];
    defaultValue?: string | null;
    groupId?: string | null;
  }>(),
  // @ts-expect-error - `withDefaults` type issue.
  { values: [], defaultValue: null, groupId: null },
);

const registry = createTabsRegistry([...values!], {
  defaultValue,
  groupId,
  onMount: onBeforeMount,
  onDestroy: onBeforeUnmount,
});

provideTabsRegistry(registry);
</script>

<template>
  <div class="tabs">
    <ul class="tabs__list" role="tablist" aria-orientation="horizontal">
      <TabItem
        v-for="value in values.filter(isString)"
        :key="value"
        :value="value"
      />

      <slot name="tablist" />
    </ul>

    <div class="tabs__panels">
      <slot />
    </div>
  </div>
</template>

<style scoped>
.tabs {
  width: 100%;
  border: var(--vbk--menu-border);
  margin: 2rem 0;
}

.tabs__list {
  display: flex;
  align-items: center;
  width: 100%;
  list-style: none;
  padding: 0.2rem;
  margin: 0;
  overflow-x: auto;
  background-color: var(--vbk--color-bg-200);
}

.tabs__panels {
  padding: 1.15rem;
}
</style>

// packages/preact/src/client/components/tabs/Tabs.tsx
import { isString } from '@vitebook/client';
import {
  createTabsRegistry,
  TabsRegistryItem,
} from '@vitebook/client/components/tabs';
import type { ComponentChildren } from 'preact';
import { useRef } from 'preact/hooks';

import { useOnDestroy } from '../../hooks/useOnDestroy';
import { useOnMount } from '../../hooks/useOnMount';
import TabItem from './TabItem';
import styles from './Tabs.module.css';
import { TabsRegistryContext } from './useTabsRegistry';

export type TabsProps = {
  values?: TabsRegistryItem[];
  defaultValue?: string | null;
  groupId?: string | null;
  tabList?: ComponentChildren;
  children: ComponentChildren;
};

function Tabs({
  values = [],
  defaultValue = null,
  groupId = null,
  tabList = null,
  children,
}: TabsProps) {
  const onMount = useOnMount();
  const onDestroy = useOnDestroy();

  const registry = useRef(
    createTabsRegistry(values, {
      defaultValue,
      groupId,
      onMount,
      onDestroy,
    }),
  );

  return (
    <TabsRegistryContext.Provider value={registry.current}>
      <div class={styles.tabs}>
        <ul
          class={styles['tabs__list']}
          role="tablist"
          aria-orientation="horizontal"
        >
          {values.filter(isString).map((value) => (
            <TabItem value={value} key={value} />
          ))}

          {tabList}
        </ul>

        <div class={styles['tabs__panels']}>{children}</div>
      </div>
    </TabsRegistryContext.Provider>
  );
}

Tabs.displayName = 'Tabs';

export default Tabs;
