// packages/theme-vue-default/src/client/components/Navbar/NavLinks.vue
<script setup lang="ts">
import { useLocalizedThemeConfig } from '../../composables/useLocalizedThemeConfig';
import NavItemLink from './NavItemLink.vue';
import NavItemWithMenu from './NavItemWithMenu.vue';
import { useLanguageLinks } from './useLanguageLinks';
import { useHasNavbarItems } from './useNavbar';
import { useRepoLink } from './useRepoLink';

const themeConfig = useLocalizedThemeConfig();
const repoLink = useRepoLink();
const languageLinks = useLanguageLinks();
const hasNavItems = useHasNavbarItems();
</script>

<template>
  <nav v-if="hasNavItems">
    <ul>
      <template v-if="hasNavItems">
        <li
          v-for="item in themeConfig.navbar.items"
          :key="item.text"
          class="nav-item"
        >
          <NavItemWithMenu v-if="'menu' in item" :item="item" />
          <NavItemLink v-else :item="item" />
        </li>
      </template>

      <li v-if="languageLinks" class="nav-item">
        <NavItemWithMenu :item="languageLinks" />
      </li>

      <li v-if="repoLink" class="nav-item">
        <NavItemLink :item="repoLink" />
      </li>
    </ul>
  </nav>
</template>

<style scoped>
nav > ul {
  margin: 0;
  padding: 0;
  list-style: none;
  display: flex;
  flex-direction: column;
}

ul > li {
  margin: 0;
  padding: 0;
}

@media (min-width: 992px) {
  nav > ul {
    flex-direction: row;
    align-items: center;
  }
}
</style>

// packages/theme-default/src/client/components/_navbar/NavLinks.svelte
<script>
  import { localizedThemeConfig } from '../../stores/localizedThemeConfig';

  import { languageLinks } from '../../stores/languageLinks';
  import { hasNavbarItems } from './hasNavbarItems';
  import { navbarConfig } from './navbarConfig';
  import NavLink from './NavLink.svelte';
  import NavMenu from './NavMenu.svelte';
  import { repoLink } from '../../stores/repoLink';

  export let active = undefined;

  $: visible =
    $hasNavbarItems ||
    $localizedThemeConfig.socials.discord ||
    $localizedThemeConfig.socials.twitter ||
    $repoLink;
</script>

{#if visible}
  <nav class="navbar__links" class:active>
    <ul class="navbar__links__list">
      {#each $navbarConfig?.items ?? [] as item (item)}
        <li class="navbar__links__list-item">
          {#if 'menu' in item}
            <NavMenu {item} />
          {:else}
            <NavLink {item} />
          {/if}
        </li>
      {/each}

      {#if $languageLinks}
        <li class="navbar__links__list-item">
          <NavMenu item={$languageLinks} />
        </li>
      {/if}
    </ul>
  </nav>
{/if}

<style>
  .navbar__links {
    display: none;
  }

  .navbar__links.active {
    display: block;
  }

  .navbar__links__list {
    margin: 0;
    padding: 0;
    list-style: none;
  }

  @media (min-width: 992px) {
    .navbar__links {
      display: block;
    }

    .navbar__links__list {
      display: flex;
      flex-direction: row;
      align-items: center;
    }

    .navbar__links__list-item {
      margin: 0 0.125rem;
    }
  }
</style>
