// packages/theme-default/src/client/components/Sidebar/Sidebar.vue
<script setup lang="ts">
import { useMediaQuery } from '@vueuse/core';
import { computed, defineAsyncComponent, ref, watch, watchEffect } from 'vue';
import { useRoute } from 'vue-router';

import BackArrowIcon from ':virtual/vitebook/icons/back-arrow?raw&vue';

import { defaultThemeLocaleOptions } from '../../../shared';
import { useLocalizedThemeConfig } from '../../composables/useLocalizedThemeConfig';
import NavbarTitle from '../Navbar/NavbarTitle.vue';
import { useHasNavbarItems } from '../Navbar/useNavbar';
import ThemeSwitch from '../ThemeSwitch.vue';
import SidebarLinks from './SidebarLinks.vue';
import { useHasSidebarItems, useIsSidebarOpen } from './useSidebar';

const route = useRoute();
const isSidebarOpen = useIsSidebarOpen();
const theme = useLocalizedThemeConfig();
const hasNavItems = useHasNavbarItems();
const hasSidebarItems = useHasSidebarItems();
const isLargeScreen = useMediaQuery('(min-width: 992px)');

const backToMainMenuText = computed(
  () =>
    theme.value.sidebar?.backToMainMenuText ??
    defaultThemeLocaleOptions.sidebar.backToMainMenuText
);

const isMainMenuShowing = ref(false);

const hasMainMenuItems = computed(() =>
  !isLargeScreen.value ? hasNavItems.value : false
);

const forceSidebarOpen = computed(
  () => isLargeScreen.value && hasSidebarItems.value
);

watch(
  () => route.path,
  () => {
    if (!forceSidebarOpen.value) isSidebarOpen.value = false;
  }
);

watchEffect(() => {
  if (isLargeScreen.value) {
    isMainMenuShowing.value = false;
  } else {
    isSidebarOpen.value = false;
  }
});

watchEffect(() => {
  if (isLargeScreen.value && !hasSidebarItems.value) {
    isSidebarOpen.value = false;
  }
});

watchEffect(() => {
  if (!isSidebarOpen.value && forceSidebarOpen.value) {
    isSidebarOpen.value = true;
  }
});

watchEffect(() => {
  isMainMenuShowing.value =
    (!isSidebarOpen.value && !hasSidebarItems.value) ||
    (!hasSidebarItems.value && hasMainMenuItems.value);
});

watchEffect(() => {
  if (isSidebarOpen.value) {
    document.documentElement.classList.add('sidebar-open');
  } else {
    document.documentElement.classList.remove('sidebar-open');
  }
});

function handleToggleMenus() {
  isMainMenuShowing.value = !isMainMenuShowing.value;
}

const NavLinks = defineAsyncComponent(() => import('../Navbar/NavLinks.vue'));
</script>

<template>
  <aside
    class="sidebar"
    :class="{ open: isSidebarOpen, 'icon-colors': theme.sidebar?.iconColors }"
    :aria-hidden="!isSidebarOpen"
  >
    <slot name="start" />

    <div
      v-if="!isLargeScreen || theme.navbar === false"
      class="sidebar__header"
    >
      <div class="sidebar__header-wrapper">
        <NavbarTitle />
        <div class="flex-grow"></div>
        <ThemeSwitch />
      </div>
    </div>

    <div class="sidebar__body">
      <button
        v-if="hasMainMenuItems"
        class="sidebar__back-button"
        :aria-hidden="isMainMenuShowing"
        @pointerdown="handleToggleMenus"
        @keydown.enter="handleToggleMenus"
      >
        <BackArrowIcon class="sidebar__back-button__arrow" />
        {{ backToMainMenuText }}
      </button>

      <NavLinks
        v-if="hasMainMenuItems"
        class="sidebar__main-menu"
        :aria-hidden="!isMainMenuShowing"
      />

      <SidebarLinks
        v-if="hasSidebarItems"
        class="sidebar__current-menu"
        :aria-hidden="isMainMenuShowing"
      />
    </div>

    <slot name="end" />
  </aside>
</template>

<style>
.sidebar {
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  flex: 0 0 auto;
  z-index: var(--vbk--sidebar-z-index);
  width: 80vw;
  background-color: var(--vbk--sidebar-bg-color);
  overflow-y: auto;
  border: var(--vbk--sidebar-border);
  transform: translateX(-100%) translateZ(0);
  transition: transform 250ms ease-in;
  will-change: transform;
  box-shadow: var(--vbk--elevation-medium);
}

.sidebar.open {
  transform: translateX(0) translateZ(0);
}

.sidebar__header {
  padding-top: 0.25rem;
}

.sidebar__header-wrapper {
  display: flex;
  padding: 1rem;
}

.sidebar__back-button {
  display: flex;
  align-items: center;
  width: 100%;
  padding: 0.5rem;
  border: 0;
  font-size: 1rem;
  margin-top: 0.2rem;
  font-weight: 500;
  border-radius: 0.12rem;
  color: var(--vbk--color-text);
  white-space: nowrap;
  text-decoration: none;
  background-color: var(--vbk--color-gray-100);
  text-align: left;
  cursor: pointer;
  line-height: 1.5;
}

.sidebar__back-button__arrow {
  margin-right: 0.25rem;
}

.sidebar__back-button[aria-hidden='true'] {
  display: none;
}

.sidebar__body {
  padding: 0 1rem;
  margin-top: 0.375rem;
}

.sidebar__main-menu {
  display: none;
}

.sidebar__main-menu[aria-hidden='false'] {
  display: block;
}

.sidebar__current-menu {
  margin-top: 1rem;
}

.sidebar__current-menu[aria-hidden='true'] {
  display: none;
}

@media (hover: hover) and (pointer: fine) {
  .sidebar__back-button:hover {
    background-color: var(--vbk--color-gray-100);
  }
}

@media (min-width: 992px) {
  .sidebar {
    position: sticky;
    width: auto;
    min-width: var(--vbk--sidebar-min-width);
    max-height: 100vh;
    opacity: 1;
    z-index: 1;
    transition: unset;
    padding-top: var(--vbk--navbar-height);
    box-shadow: unset;
  }

  .sidebar.open {
    border-right: 0.125rem solid var(--vbk--color-gray-200);
  }

  html.dark .sidebar {
    border-right: 0.125rem solid var(--vbk--color-gray-500);
  }

  .sidebar:not(.sidebar.open) {
    width: 0;
    min-width: 0;
    opacity: 0;
    visibility: hidden;
  }

  .sidebar__header {
    /* display: none; */
  }

  .sidebar__back-button {
    display: none;
  }
}
</style>

// packages/theme-default/src/client/components/sidebar/Sidebar.svelte
<script>
  import BackArrowIcon from ':virtual/vitebook/icons/back-arrow?raw';
  import { currentRoute } from '@vitebook/client';
  import { defaultThemeLocaleOptions } from '../../../shared';
  import { darkMode } from '../../stores/darkMode';
  import { isLargeScreen } from '../../stores/isLargeScreen';
  import { localizedThemeConfig } from '../../stores/localizedThemeConfig';
  import { hasNavbarItems } from '../navbar/hasNavbarItems';
  import NavbarTitle from '../navbar/NavbarTitle.svelte';
  import ThemeSwitch from '../ThemeSwitch.svelte';
  import DiscordLink from '../links/DiscordLink.svelte';
  import RepoLink from '../links/RepoLink.svelte';
  import TwitterLink from '../links/TwitterLink.svelte';
  import { hasSidebarItems } from './hasSidebarItems';
  import { multiSidebarStyleConfig } from './multiSidebarStyleConfig';
  import SidebarButton from './SidebarButton.svelte';
  import { sidebarItems } from './sidebarItems';
  import SidebarTree from './SidebarTree.svelte';

  export let open = false;

  let sidebarBodyRef;
  let isMainMenuShowing = false;

  $: backToMainMenuText =
    $localizedThemeConfig.sidebar?.backToMainMenuText ??
    defaultThemeLocaleOptions.sidebar.backToMainMenuText;

  $: iconColors =
    $multiSidebarStyleConfig.iconColors ??
    $localizedThemeConfig.sidebar?.iconColors;

  $: hasMainMenuItems = !$isLargeScreen ? $hasNavbarItems : false;

  $: isMainMenuShowing =
    (!open && !$hasSidebarItems) || (!$hasSidebarItems && hasMainMenuItems);

  $: forceOpen = $isLargeScreen && $hasSidebarItems;

  // Close sidebar on route change if not forced open.
  $: if ($currentRoute && !forceOpen) open = false;

  // Hide main menu once enter large screen, otherwise hide sidebar on smaller devices.
  $: if ($isLargeScreen) {
    isMainMenuShowing = false;
  } else {
    open = false;
  }

  // If large screen and no sidebar items hide it.
  $: if ($isLargeScreen && !$hasSidebarItems) {
    open = false;
  }

  // force open.
  $: if (!open && forceOpen) {
    open = true;
  }

  function onShowMainMenu() {
    isMainMenuShowing = true;
  }

  $: hasHeader = !$isLargeScreen || $localizedThemeConfig.navbar === false;
</script>

<aside
  class="sidebar"
  class:dark={$darkMode}
  class:open
  class:icon-colors={iconColors}
  aria-hidden={!open}
>
  <slot name="start" />

  {#if hasHeader}
    <div class="sidebar__header">
      <div class="sidebar__header-wrapper">
        <NavbarTitle />
        <div style="flex-grow: 1; margin-left: 2.5rem;" />
        <TwitterLink />
        <DiscordLink />
        <RepoLink />
        <ThemeSwitch />
      </div>
    </div>
  {/if}

  <div class="sidebar__body" bind:this={sidebarBodyRef}>
    {#if hasMainMenuItems && !$isLargeScreen && !isMainMenuShowing}
      <SidebarButton
        class="sidebar__back-button"
        aria-hidden={isMainMenuShowing}
        on:pointerdown={onShowMainMenu}
        on:keydown={(e) => e.key === 'Enter' && onShowMainMenu()}
      >
        <span class="sidebar__back-button__arrow">
          {@html BackArrowIcon}
        </span>
        {backToMainMenuText}
      </SidebarButton>
    {/if}

    {#if hasMainMenuItems}
      <div class="sidebar__main-menu" aria-hidden={!isMainMenuShowing}>
        {#await import('../navbar/NavLinks.svelte') then NavLinks}
          <svelte:component
            this={NavLinks.default}
            active={isMainMenuShowing}
          />
        {/await}
      </div>
    {/if}

    {#if $hasSidebarItems}
      <ul class="sidebar__current-menu" aria-hidden={isMainMenuShowing}>
        <SidebarTree items={$sidebarItems} />
      </ul>
    {/if}
  </div>

  <slot name="end" />
</aside>

<style>
  .sidebar {
    --vbk--nav-item-color: var(--vbk--sidebar-item-color);
    --vbk--nav-item-bg-color: var(--vbk--sidebar-item-bg-color);
    --vbk--nav-item-hover-color: var(--vbk--sidebar-item-hover-color);
    --vbk--nav-item-hover-bg-color: var(--vbk--sidebar-item-hover-bg-color);
    --vbk--nav-link-active-bg-color: transparent;

    display: flex;
    flex-direction: column;
    position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
    flex: 0 0 auto;
    z-index: var(--vbk--sidebar-z-index);
    min-width: 80vw;
    background-color: var(--vbk--sidebar-bg-color);
    overflow-y: auto;
    border: var(--vbk--sidebar-border);
    transform: translateX(-100%) translateZ(0);
    transition: transform 250ms ease-in;
    will-change: transform;
    box-shadow: var(--vbk--elevation-medium);
  }

  .sidebar.open {
    transform: translateX(0) translateZ(0);
  }

  .sidebar__header {
    position: sticky;
    top: 0;
    left: 0;
    padding-top: 0.25rem;
    background-color: var(--vbk--sidebar-bg-color);
  }

  .sidebar__header-wrapper {
    display: flex;
    padding: 1rem;
  }

  .sidebar__back-button__arrow {
    margin-right: 0.25rem;
  }

  .sidebar__body {
    flex: 1 0 0;
    padding: 0 1rem;
    padding-bottom: 2.5rem;
    overflow-x: hidden;
  }

  .sidebar__main-menu {
    display: none;
  }

  .sidebar__main-menu[aria-hidden='false'] {
    display: block;
  }

  .sidebar__current-menu {
    padding: 0;
    margin: 0;
    margin-top: 0.75rem;
  }

  .sidebar__current-menu[aria-hidden='true'] {
    display: none;
  }

  @media (min-width: 992px) {
    .sidebar {
      position: sticky;
      width: auto;
      min-width: var(--vbk--sidebar-min-width);
      max-height: 100vh;
      opacity: 1;
      z-index: 1;
      transition: unset;
      padding-top: var(--vbk--navbar-height);
      box-shadow: unset;
    }

    .sidebar.open {
      border-right: 0.125rem solid var(--vbk--color-gray-200);
    }

    .sidebar.open.dark {
      border-color: var(--vbk--color-gray-500);
    }

    .sidebar:not(.sidebar.open) {
      width: 0;
      min-width: 0;
      opacity: 0;
      visibility: hidden;
    }
  }
</style>
