// packages/theme-vue-default/src/client/components/Navbar/NavbarTitle.vue
<script setup lang="ts">
import {
  useLocalizedSiteOptions,
  useRouteLocale,
  withBaseUrl
} from '@vitebook/vue/client';

import { useLocalizedThemeConfig } from '../../composables/useLocalizedThemeConfig';

const siteConfig = useLocalizedSiteOptions();
const themeConfig = useLocalizedThemeConfig();
const localePath = useRouteLocale();
</script>

<template>
  <router-link
    class="title"
    :to="localePath"
    :aria-label="`${siteConfig.title}, ${themeConfig.notFoundPage.goHomeText}`"
  >
    <img
      v-if="themeConfig.logo"
      class="logo"
      :src="withBaseUrl(themeConfig.logo)"
      :alt="`${siteConfig.title} logo`"
    />
    {{ siteConfig.title }}
  </router-link>
</template>

<style scoped>
.title {
  font-size: 1.3rem;
  font-weight: 500;
  color: var(--color-text);
  transition: transform 150ms ease;
  padding-top: 0.2rem;
  padding-right: 0.2rem;
  text-decoration: none;
}

@media (hover: hover) and (pointer: fine) {
  .title:hover {
    text-decoration: none;
    transform: scale(1.02);
  }
}

.logo {
  width: 2rem;
  height: 2rem;
  margin-right: 0.2rem;
  vertical-align: middle;
}
</style>

// packages/theme-default/src/client/components/Navbar/NavbarTitle.svelte
<script>
  import Logo from ':virtual/vitebook/logo.svg';
  import { currentRouteLocale, localizedSiteOptions } from '@vitebook/client';
  import { defaultThemeLocaleOptions } from '../../../shared';
  import { localizedThemeConfig } from '../../stores/localizedThemeConfig';

  $: goHomeText =
    $localizedThemeConfig.notFoundPage?.goHomeText ??
    defaultThemeLocaleOptions.notFoundPage.goHomeText;
</script>

<a
  class="navbar__title"
  href={$currentRouteLocale}
  aria-label={`${$localizedSiteOptions.title}, ${goHomeText}`}
>
  <div class="navbar__logo">
    {@html Logo}
  </div>
  {$localizedSiteOptions.title}
</a>

<style>
  .navbar__title {
    display: flex;
    align-items: center;
    font-size: 1.3rem;
    font-weight: 500;
    letter-spacing: 0.01rem;
    color: var(--vbk--navbar-title-color);
    transition: transform 150ms ease;
    padding-top: 0.2rem;
    padding-right: 0.2rem;
    text-decoration: none;
  }

  @media (hover: hover) and (pointer: fine) {
    .navbar__title:hover {
      text-decoration: none;
      backface-visibility: hidden;
      transform: scale(1.05) translateZ(0);
    }
  }

  .navbar__logo {
    width: 2rem;
    height: 2rem;
    margin-right: 0.2rem;
    vertical-align: middle;
    transition: var(--vbk--navbar-logo-transition);
    color: var(--vbk--navbar-logo-color);
  }
</style>
