// packages/theme-default/src/client/components/Navbar/NavLinks.svelte
<script>
  import { languageLinks } from '../../stores/languageLinks';
  import { repoLink } from '../../stores/repoLink';
  import { hasNavbarItems } from './hasNavbarItems';
  import { navbarConfig } from './navbarConfig';
  import NavItemLink from './NavItemLink.svelte';
  import NavItemWithMenu from './NavItemWithMenu.svelte';
</script>

{#if $hasNavbarItems}
  <nav class="navbar__links">
    <ul class="navbar__links__list">
      {#each $navbarConfig?.items ?? [] as item (item.text)}
        <li class="navbar__links__list-item">
          {#if 'menu' in item}
            <NavItemWithMenu {item} />
          {:else}
            <NavItemLink {item} />
          {/if}
        </li>
      {/each}

      {#if $languageLinks}
        <li class="navbar__links__list-item">
          <NavItemWithMenu item={$languageLinks} />
        </li>
      {/if}

      {#if $repoLink}
        <li class="navbar__links__list-item">
          <NavItemLink item={$repoLink} />
        </li>
      {/if}
    </ul>
  </nav>
{/if}

<style>
  .navbar__links {
    display: none;
  }

  @media (min-width: 992px) {
    .navbar__links {
      display: block;
    }

    .navbar__links__list {
      display: flex;
      flex-direction: row;
      align-items: center;
    }
  }
</style>

// packages/theme-default/src/client/components/Navbar/NavLinks.vue
<script setup lang="ts">
import NavItemLink from './NavItemLink.vue';
import NavItemWithMenu from './NavItemWithMenu.vue';
import { useLanguageLinks } from './useLanguageLinks';
import { useHasNavbarItems, useNavbarConfig } from './useNavbar';
import { useRepoLink } from './useRepoLink';

const navbar = useNavbarConfig();
const repoLink = useRepoLink();
const languageLinks = useLanguageLinks();
const hasNavItems = useHasNavbarItems();
</script>

<template>
  <nav v-if="hasNavItems" class="navbar__links">
    <ul class="navbar__links__list">
      <template v-if="hasNavItems">
        <li
          v-for="item in navbar?.items ?? []"
          :key="item.text"
          class="navbar__links__list-item"
        >
          <NavItemWithMenu v-if="'menu' in item" :item="item" />
          <NavItemLink v-else :item="item" />
        </li>
      </template>

      <li v-if="languageLinks" class="navbar__links__list-item">
        <NavItemWithMenu :item="languageLinks" />
      </li>

      <li v-if="repoLink" class="navbar__links__list-item">
        <NavItemLink :item="repoLink" />
      </li>
    </ul>
  </nav>
</template>
