// packages/vue/src/client/components/OutboundLink.vue
<template>
  <svg
    class="external-link"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    aria-hidden="true"
    role="img"
    width="15"
    height="15"
    preserveAspectRatio="xMidYMid meet"
    viewBox="0 0 24 24"
  >
    <g fill="none">
      <path
        d="M10 6H6a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-4M14 4h6m0 0v6m0-6L10 14"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </g>
  </svg>
</template>

<style scoped>
svg {
  position: relative;
  display: inline-block;
  color: #aaa;
  vertical-align: middle;
  top: -1px;
}
</style>

// packages/client/src/client/components/OutboundLink.svelte
<svg
  class="external-link"
  xmlns="http://www.w3.org/2000/svg"
  xmlns:xlink="http://www.w3.org/1999/xlink"
  aria-hidden="true"
  role="img"
  width="15"
  height="15"
  preserveAspectRatio="xMidYMid meet"
  viewBox="0 0 24 24"
>
  <g fill="none">
    <path
      d="M10 6H6a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-4M14 4h6m0 0v6m0-6L10 14"
      stroke="currentColor"
      stroke-width="2"
      stroke-linecap="round"
      stroke-linejoin="round"
    />
  </g>
</svg>

<style>
  svg {
    position: relative;
    display: inline-block;
    color: #aaa;
    vertical-align: middle;
    top: -1px;
  }
</style>
