// packages/vue/src/client/components/Variant.vue
<script setup lang="ts">
import { inBrowser } from '@vitebook/core/shared';

import { onMounted, onBeforeUnmount } from 'vue';
import { variants } from '@vitebook/client';
import { useActiveVariant, useVariants } from '../composables/useVariants';

const props = defineProps<{
  name: string;
  description?: string;
}>();

const variantId = encodeURI(`${props.name}`.toLowerCase());

const searchParams = inBrowser
  ? new URL(location.href).searchParams
  : undefined;

const $variants = useVariants();
const $activeVariant = useActiveVariant();

const variant = {
  id: variantId,
  name: `${props.name}`,
  description: props.description,
  active: import.meta.env.SSR
    ? Object.values($variants.value).length === 0 ||
      Object.values($variants.value).findIndex((v) => v.id === variantId) === 0
    : searchParams?.get('variant')?.toLowerCase() === variantId
};

variants.add(variant);

onMounted(() => {
  if (!$activeVariant.value) {
    const variations = Object.values($variants.value);
    variants.setActive(variations[0].id);
  } else if ($activeVariant.value) {
    // Simply updating query string and other information.
    variants.setActive($activeVariant.value.id);
  }
});

onBeforeUnmount(() => {
  variants.delete(variantId);
});
</script>

<template>
  <slot v-if="$variants[variantId].active" />
</template>

// packages/preact/src/client/components/Variant.tsx
import { activeVariant, inBrowser, variants } from '@vitebook/client';
import type { ComponentChildren } from 'preact';
import { useEffect, useRef } from 'preact/hooks';
import { get } from 'svelte/store';

import { useVariants } from '../hooks/useVariants';

export type VariantProps = {
  name: string;
  description?: string;
  children: ComponentChildren;
};

function Variant({ name, description, children }: VariantProps) {
  const variantId = useRef(encodeURI(`${name}`.toLowerCase()));
  const hasAddedVariant = useRef(false);

  const searchParams = useRef(
    inBrowser ? new URL(location.href).searchParams : undefined,
  );

  // Only used to trigger re-renders - updates too slow for our needs.
  const _ = useVariants();

  if (!hasAddedVariant.current) {
    const variant = {
      id: variantId.current,
      name: `${name}`,
      description: description,
      active: import.meta.env.SSR
        ? Object.values(get(variants)).length === 0 ||
          Object.values(get(variants)).findIndex(
            (v) => v.id === variantId.current,
          ) === 0
        : searchParams.current?.get('variant')?.toLowerCase() ===
          variantId.current,
    };

    variants.add(variant);

    hasAddedVariant.current = true;
  }

  useEffect(() => {
    // Hooks are updated too slow, need to get fresh values from store.
    const active = get(activeVariant);
    const variations = Object.values(get(variants));

    if (!active) {
      variants.setActive(variations[0].id);
    } else if (active) {
      // Simply updating query string and other information.
      variants.setActive(active.id);
    }

    return () => {
      variants.delete(variantId.current);
    };
  }, []);

  return <>{get(variants)[variantId.current]?.active && children}</>;
}

Variant.displayName = 'Variant';

export default Variant;
